export const surpriseMePrompts = [
  "An abstract sculpture of a giant hand holding an intricate crystal ball, made from metal and glass",
  "A portrait painting of a lion wearing a monocle and top hat, set against a vibrant pink background",
  "A photograph of a snowy owl perched on a tree branch, with a dark and moody atmosphere",
  "A digital art depiction of a cityscape at night, with towering skyscrapers illuminated in neon lights",
  "A surreal oil painting of a humanoid creature with multiple arms and eyes, playing a grand piano",
  "A colorful illustration of a unicorn prancing through a field of flowers, with a rainbow in the background",
  "A photograph of a cascading waterfall surrounded by lush green foliage, with mist rising from the water",
  "A portrait painting of a woman with long flowing hair, wearing a mask made of flowers",
  "A 3D rendering of a futuristic city in the clouds, with flying cars and hovering buildings",
  "A photograph of a majestic humpback whale breaching the surface of the ocean, with the sun setting in the background",
  "A digital painting of a giant octopus wrapped around a lighthouse, with storm clouds gathering in the sky",
  "A whimsical illustration of a group of animals having a tea party in a forest clearing",
  "A photograph of a field of lavender in bloom, with the sun setting behind a distant mountain range",
  "A mixed media sculpture of a tree with roots made from glass and leaves made from metal",
  "A portrait painting of a mermaid lounging on a rock in the ocean, with her hair flowing in the wind",
  "A photograph of a desert landscape at sunset, with cacti silhouetted against the orange sky",
  "An oil painting of a ship sailing through a stormy sea, with lightning illuminating the waves",
  "A digital art depiction of a futuristic city with towering buildings and a monorail running through it",
  "A watercolor painting of a field of wildflowers with a beautiful sunset in the background",
  "A photograph of a majestic eagle perched on a tree branch, with a snow-capped mountain in the background",
  "A sculpture of a dragon made from recycled metal parts and machinery",
  "A surrealist painting of a clock melting in a barren desert landscape",
  "A digital art illustration of a cybernetic dragon flying through a neon-lit cityscape",
  "A photograph of a peaceful stream flowing through a lush forest, with a wooden footbridge crossing over it",
  "A mixed media sculpture of a phoenix rising from the ashes, made from wood and metal",
  "A portrait painting of a beautiful woman wearing a dress made from flowers, with a peaceful garden in the background",
  "A digital art depiction of a group of astronauts exploring a strange planet with multiple moons in the sky",
  "A watercolor painting of a peaceful beach scene with palm trees and a crystal-clear blue ocean",
  "A photograph of a herd of wild horses galloping through a wide open prairie",
  "An oil painting of a majestic lion standing on a rocky outcropping overlooking a vast savanna",
];
