import React, { useState, useEffect } from "react";
import { Card, Form, Loader } from "../components";

//rendering all images in Card component
const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map((image) => <Card key={image._id} {...image} />);
  }
  return (
    <h2 className="mt-5 text-xl font-bold uppercase text-[#6449ff]">{title}</h2>
  );
};

const Home = () => {
  const [loading, setLoading] = useState(false);
  const [images, setImages] = useState(null);
  const [searchText, setSearchText] = useState("");
  return (
    <section className="mx-auto max-w-7xl">
      <div>
        <h1 className="text-[32px] font-extrabold text-black">Latest Images</h1>
        <p className="mt-2 max-w-[500px] text-[14px] text-gray-400">
          Discover collection of latest images generated by out visitors
        </p>
      </div>
      <div className="mt-16">
        <Form />
      </div>
      <div className="mt-10">
        {loading ? (
          <div className="flex items-center justify-center">
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className="mb-3 text-xl font-medium text-gray-400">
                Results for <span className="text-black">{searchText}</span>
              </h2>
            )}
            {/* Images */}
            <div className="grid grid-cols-1 gap-3 xs:grid-cols-2 sm:grid-cols-3 lg:grid-cols-4">
              {searchText ? (
                <RenderCards data={[]} title="No images found" />
              ) : (
                <RenderCards data={[]} title="No images found" />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
};

export default Home;
